repos:
  - repo:
      https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
    rev: v0.11.8
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pdm-project/pdm
    rev: 2.26.9
    hooks:
      - id: pdm-export
        args: ["-o", "requirements.txt", "--without-hashes"]
        files: ^pylock.toml$
