[project]
name = "xmlparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <4"
dependencies = [
    "nltk>=3.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
